import React, { useState } from 'react';
import { View, Text, StyleSheet, TextInput, TouchableOpacity, ActivityIndicator, Alert, ScrollView } from 'react-native';
import { useTranslation } from 'react-i18next';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuth, AccountType } from '../context/AuthContext';
import { Phone, User, ChevronLeft, ShieldCheck } from 'lucide-react-native';
import Logo from '../components/Logo';

export default function RegisterScreen({ navigation }: any) {
  const { t } = useTranslation();
  const { register, isLoading } = useAuth();
  const [phone, setPhone] = useState('');
  const [selectedType, setSelectedType] = useState<AccountType>('standard');
  const [step, setStep] = useState<'form' | 'success'>('form');

  const handleRegister = async () => {
    if (!phone) {
      Alert.alert(t('common.error'), t('auth.phoneRequired'));
      return;
    }

    // PIN is usually generated by backend and sent by SMS in this app
    // But the context says register(phone, pin, type)
    // Looking at Auth.tsx, it sends { phone, type } to /register
    const success = await register(phone, '', selectedType);
    if (success) {
      setStep('success');
    } else {
      Alert.alert(t('common.error'), t('auth.creationError'));
    }
  };

  if (step === 'success') {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.successContent}>
          <Logo size={100} />
          <View style={styles.successIcon}>
            <ShieldCheck color="#22c55e" size={64} />
          </View>
          <Text style={styles.successTitle}>{t('auth.accountCreated')}</Text>
          <Text style={styles.successDesc}>{t('auth.keepPin')}</Text>
          <TouchableOpacity 
            style={styles.primaryButton}
            onPress={() => navigation.navigate('Login')}
          >
            <Text style={styles.primaryButtonText}>{t('auth.continue')}</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <ChevronLeft color="#0f172a" size={24} />
        </TouchableOpacity>
        <Logo size={40} showText={false} />
        <Text style={styles.headerTitle}>{t('auth.registerTitle')}</Text>
      </View>

      <ScrollView contentContainerStyle={styles.scrollContent}>
        <View style={styles.inputGroup}>
          <Text style={styles.label}>{t('auth.phone')}</Text>
          <View style={styles.inputWrapper}>
            <Phone color="#94a3b8" size={20} style={styles.inputIcon} />
            <TextInput
              style={styles.input}
              placeholder="Ex: 0123456789"
              value={phone}
              onChangeText={setPhone}
              keyboardType="phone-pad"
              placeholderTextColor="#94a3b8"
            />
          </View>
        </View>

        <View style={styles.inputGroup}>
          <Text style={styles.label}>{t('profile.accountType')}</Text>
          <View style={styles.typeGrid}>
            {(['standard', 'professional', 'pharmacist'] as AccountType[]).map((type) => (
              <TouchableOpacity
                key={type}
                style={[
                  styles.typeCard,
                  selectedType === type && styles.selectedTypeCard
                ]}
                onPress={() => setSelectedType(type)}
              >
                <Text style={[
                  styles.typeLabel,
                  selectedType === type && styles.selectedTypeLabel
                ]}>
                  {t(`profile.${type}`)}
                </Text>
              </TouchableOpacity>
            ))}
          </View>
        </View>

        <TouchableOpacity 
          style={[styles.primaryButton, isLoading && styles.disabledButton]}
          onPress={handleRegister}
          disabled={isLoading}
        >
          {isLoading ? (
            <ActivityIndicator color="#fff" />
          ) : (
            <Text style={styles.primaryButtonText}>{t('auth.signUp')}</Text>
          )}
        </TouchableOpacity>

        <View style={styles.footer}>
          <Text style={styles.footerText}>{t('index.loginPrompt')}</Text>
          <TouchableOpacity onPress={() => navigation.navigate('Login')}>
            <Text style={styles.loginLink}> {t('auth.loginTitle')}</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 24,
    gap: 16,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0f172a',
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  inputGroup: {
    marginBottom: 24,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#475569',
    marginBottom: 8,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 16,
    backgroundColor: '#f8fafc',
  },
  inputIcon: {
    marginRight: 12,
  },
  input: {
    flex: 1,
    height: 52,
    fontSize: 16,
    color: '#0f172a',
  },
  typeGrid: {
    gap: 12,
  },
  typeCard: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
  },
  selectedTypeCard: {
    borderColor: '#2563eb',
    backgroundColor: '#eff6ff',
  },
  typeLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#475569',
    textAlign: 'center',
  },
  selectedTypeLabel: {
    color: '#2563eb',
  },
  primaryButton: {
    backgroundColor: '#2563eb',
    height: 56,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  disabledButton: {
    opacity: 0.7,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 32,
  },
  footerText: {
    color: '#64748b',
    fontSize: 14,
  },
  loginLink: {
    color: '#2563eb',
    fontSize: 14,
    fontWeight: '700',
  },
  successContent: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  successIcon: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#f0fdf4',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
  },
  successTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#0f172a',
    textAlign: 'center',
    marginBottom: 16,
  },
  successDesc: {
    fontSize: 16,
    color: '#64748b',
    textAlign: 'center',
    marginBottom: 40,
    lineHeight: 24,
  },
});
